### ISSUE TITLE
Incompatibility with App extension

### ISSUE THREAD

**Issue by StevenWatremez** [at-internet/atinternet-ios-objc-sdk#1]
In your pod you are an UIApplication reference. So I can't implement your pod for App extension and tag all View on the App extension. I have this following error.

![screen shot 2015-11-19 at 18 14 53](https://cloud.githubusercontent.com/assets/11426754/11278043/7de01384-8ee9-11e5-9425-3e91cc1f67c4.png)

**Comment by d-theo** [comment]
Can you post your pod file ?

**Comment by StevenWatremez** [comment]
I am using this pod : 
pod 'ATInternet-iOS-ObjC-SDK', '~> 2.0'

before my update I used : 
pod 'ATInternet', '~> 1.5'

**Comment by d-theo** [comment]
In order to use to SDK for the Watch Extension we had to use 2 pod subspec as explained in the documentation (/iOS and /WatchExtension) : 

```
target 'MyProject' do
pod "ATInternet-iOS-ObjC-SDK/iOS",">=2.0"
end

target 'MyProject WatchKit 1 Extension' do
pod "ATInternet-iOS-ObjC-SDK/WatchExtension", ">=2.0"
end

target 'MyProject WatchKit 1 App' do
end

**Comment by d-theo** [comment]
Which App Extension are you doing ?
I made a mistake with the pod subspec naming (I though it would be only used for the watch), but it should work as expected by using the pod WatchExtension subspec in your extension

```
target 'MyProject' do
pod "ATInternet-iOS-ObjC-SDK/iOS",">=2.0"
end

target 'MyProject App Extension' do
pod "ATInternet-iOS-ObjC-SDK/WatchExtension", ">=2.0"
end
```

I will update the podspec and the readme soon

**Comment by StevenWatremez** [comment]
I am using Action Extension. You support this extension ? How can I implement it with your pod like WatchExtension ?

**Comment by d-theo** [comment]
in your Podfile you should have a line for your app and one for your extension (one for each target) : 

![targets](https://cloud.githubusercontent.com/assets/14891777/11296590/561e7f54-8f73-11e5-9cba-e131a3842e68.png)

```
// Podfile
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
# Pods that will go in your iOS App
target 'TestAction' do
pod "ATInternet-iOS-ObjC-SDK/iOS", ">=2.0"
end

# Pods that will go in your Extension App
target 'action' do
pod "ATInternet-iOS-ObjC-SDK/WatchExtension", ">=2.0"
end
```

**Comment by StevenWatremez** [comment]
Ok so I tried the v2.0.9 version of your pod but I can't refactor all my code to implement this new version. Can I use the pod v1.5 with app extension ?

**Comment by ghost** [comment]
We never published a Pod with a version below 2.0. If you want to use SDK 1.5 you can't rely on CocoaPods.

**Comment by StevenWatremez** [comment]
Ok I understand. Before my pod update I had the pod v1.5. I had some crash on it with the App extension and I decided to update the pod. But now when I see what I need to implement to use the V2.0.9. I think it is not worth for now.

**Comment by evixar** [comment]
Where did you find the pod v1.5 ? We've never published this version on cocoapod. The only available version of our SDK on Cocoapods starts at 2.0.0.
Our SDK 2.0 is a totally new SDK that is not compatible with 1.5

Regards

**Comment by StevenWatremez** [comment]
We work with an ATInternet partner. For our problem we will call your customer service. Thanks for your answers.
Regards
