### ISSUE TITLE
setStringParam fails on parseJSONString

### ISSUE THREAD

**Issue by mitschoko** [at-internet/atinternet-ios-objc-sdk#11]
I used a pre compiled library our client sent us and tried versioned compiled form the 2.2.0 and 2.2.2 branch. And always ended up having the same issue.

When i call [ATTracker dispatch] i get the error.

`__NSCFConstantString parseJSONString]: unrecognized selector sent to instance`

it fails in **ATTracker.m** in the **setStringParam** function on the line

`if([value parseJSONString] == nil) {`

with value in this case being 

`@"screen"`

at that time. Wich originated form a hardcoded string in the setEvent Function in ATScreen. So i guess it is not due to me having some misconfiguration on the code level.

As this error occurs on some basic NS class i guess it is some Library / Linking issue. When the parseJSONString throws instead of returning a nil value.

**Comment by evixar** [comment]
Hi,

Looks like you forgot to add the "-ObjC" flag in the "Other linker flags" in the build settings as specified in our documentation (http://developers.atinternet-solutions.com/apple-en/getting-started-apple-en/integration-of-the-objective-c-library-apple-en/) 

Please let us know if this solves your problem

Regards

**Comment by mitschoko** [comment]
That broke the rest of the project. But i could fix, now it  seems to work ( At the App crashes with another error message now ).
