### ISSUE TITLE
Rare NSInvalidArgumentException while sending offline hits

### ISSUE THREAD

**Issue by Sealos** [at-internet/atinternet-ios-objc-sdk#13]
Hello, we're hitting a rare crash on some cases. I haven't been able to reproduce it locally, or to isolate the problem.

The stack is the following:

> Fatal Exception: NSInvalidArgumentException
> +entityForName: nil is not a legal NSPersistentStoreCoordinator for searching for entity name 'ATStoredOfflineHit'

> 0  CoreFoundation                 0x1939561c0 __exceptionPreprocess
> 1  libobjc.A.dylib                0x19239055c objc_exception_throw
> 2  CoreData                       0x195c27780 -[NSManagedObjectContext persistentStoreCoordinator]
> 3  ATTracker                      0x10085e2c8 -[ATStorage count] (ATStorage.m:345)
> 4  ATTracker                      0x100862ef0 +[ATSender sendOfflineHits:forceSendOfflineHits:async:] (ATSender.m:395)
> 5  ATTracker                      0x100860c44 -[ATSender sendWithOfflineHits] (ATSender.m:119)
> 6  ATTracker                      0x10084c530 -[ATBuilder main] (ATBuilder.m:394)
> 7  Foundation                     0x19434f8c4 -[__NSOperationInternal _start:]
> 8  Foundation                     0x19441cb00 __NSOQSchedule_f
> 9  libdispatch.dylib              0x1927e11c0 _dispatch_client_callout
> 10 libdispatch.dylib              0x1927ef444 _dispatch_queue_serial_drain
> 11 libdispatch.dylib              0x1927e49a8 _dispatch_queue_invoke
> 12 libdispatch.dylib              0x1927f138c _dispatch_root_queue_drain
> 13 libdispatch.dylib              0x1927f10ec _dispatch_worker_thread3
> 14 libsystem_pthread.dylib        0x1929ea2b8 _pthread_wqthread
> 15 libsystem_pthread.dylib        0x1929e9da4 start_wqthread

Thanks in advance.

**Comment by d-theo** [comment]
Hello Sealos,

Can you provide the tracker version you are working with ?

**Comment by Sealos** [comment]
My bad! forgot to include it. We're using the tagged 2.2.4 version.

**Comment by d-theo** [comment]
Hi again,

I just deployed v2.2.7, which feature : 

- The ability to shutdown completely the CoreData stack if the property "storage" in ATDefaultConfiguration.plist is set to "never" (disabling the offline mode)
- A better error handling when CoreData initialization fails.
- More verbose errors if CoreData initialization still fails.

Regards

**Comment by Sealos** [comment]
Thanks a bunch! I'll try it out and check back as soon as we push a new version.

**Comment by Sealos** [comment]
I have released a new version of the app and the crash appears to be gone! Thanks for the quick reply & fix. I'll give it more time to roll out and report back if needed!
