### ISSUE TITLE
[Bug]Percent encoding is not opted on within self promotion object

### ISSUE THREAD

**Issue by wangshengjia** [at-internet/atinternet-ios-objc-sdk#2]
Call `sendImpression` or `sendTouch` in `selfPromotion` always failure with message `Hit could not be parsed and sent : %@", self.hit.url` because url has not been encoded.

It seems to me that  `option.encode = YES;` is forgotten to be added right behind [here](https://github.com/at-internet/atinternet-ios-objc-sdk/blob/master/Tracker/Tracker/ATSelfPromotion.m#L92)

**Comment by wangshengjia** [comment]
Any idea, please?
- Maybe I'm wrong, I might not use SDK correctly. In this case, could you confirm it and point the right way to me please?
- Maybe I'm right, it's actually an issue from SDK. In this case, do you have an idea of workaround?

**Comment by BenDz** [comment]
Sorry for the delay.
We are aware of this, a patch has been scheduled in the next few weeks.
Thanks for the report.
Ben

**Comment by wangshengjia** [comment]
Cool, thank you for replying. So in your opinion, could I just add `option.encode = YES` as a temporary workaround until you release the patch officially, which means that won't cause some unknown side effect ?

**Comment by d-theo** [comment]
We fixed the issue this morning :)
