### ISSUE TITLE
Default “storage” value in configuration

### ISSUE THREAD

**Issue by wangshengjia** [at-internet/atinternet-ios-objc-sdk#3]
In your documentation [here](http://developers.atinternet-solutions.com/apple-fr/fonctionnalites-avancees-apple-fr/hits-hors-connexion-apple-fr/) and [here](http://developers.atinternet-solutions.com/apple-fr/bien-commencer-apple-fr/configuration-apple-fr/), I've been told that `required` is the default value of `storage`.

However, I may be wrong.. but apparently this is not true: [ATDefaultConfiguration.plist](https://github.com/at-internet/atinternet-ios-objc-sdk/blob/2.0.9.1/Tracker/Tracker/ATDefaultConfiguration.plist#L22)

**Comment by evixar** [comment]
Hi,

Seems like there's a mistake in our documentation. The default value is "never". Offline mode is an option. If you have this option activated you can use the "always" or "required" mode. Otherwise, hits will be ignored.

We will change the documentation.

Thanks

**Comment by wangshengjia** [comment]
Cool, thanks a lot for the information :+1:
