### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by marlontojal** [at-internet/atinternet-ios-objc-sdk#8]
Can you add carthage support?

**Comment by d-theo** [comment]
Hi,
Carthage does not support static library, sorry !
However you can use our[ Swift library](https://github.com/at-internet/atinternet-ios-swift-sdk) that is carthage compatible

**Comment by marlontojal** [comment]
It seems that its not possible to use that swift library using carthage.
When you try to import the Library you don't have access to ATInternet class. It seems that Tracker.framework only has Crash and Hash headers

**Comment by evixar** [comment]
Hi,

Is your app written in Objective-C or Swift ? 

Our Swift SDK is pure Swift (not compatible with ObjC). We are planning on making it compatible but not before few months.
If your app is writting in ObjC, you must use our ObjC library. You can use Cocoapod with this library.

Regards

**Comment by marlontojal** [comment]
Its written in ObjC, thats why I asked if you could add carthage support to this library

**Comment by evixar** [comment]
In order to support Carthage for our ObjC Library we would have to convert it to a Framework which is not planned anytime soon. Please use Cocoapod in order to use our ObjC library
